# 1
Code to convert a list of numeric values into an one-dimensional NumPy array

In [1]:
import numpy as np

num = [1,2,3,4,5]
num_array = np.array(num)

print(num)
print(num_array)
print(type(num))
print(type(num_array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


# 2
Code to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
matrix = np.arange(2,11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 3
Code to append values at the end of an array

In [3]:
num_array = np.append(num_array,[6])
print(num_array)

[1 2 3 4 5 6]


# 4
Code to create another shape from an array without changing its data (3X2 to 2X3)

In [4]:
num1 = [[1,2,3],[4,5,6]]
matrix1 = np.array(num1)
matrix1 = matrix1.reshape(3,2)
print("3X2 Array :-")
print(matrix1)
matrix2 = matrix1.reshape(2,3)
print("2X3 Array :-")
print(matrix2)

3X2 Array :-
[[1 2]
 [3 4]
 [5 6]]
2X3 Array :-
[[1 2 3]
 [4 5 6]]
